name: Test
on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run Black linter
        run: |
          black dbt_invoke tests setup.py --check --diff --color -S -l 79
  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.x]
        dbt-version: [0.18.x, 0.19.x, 1.x]
        exclude:
          - python-version: 3.x
            dbt-version: 0.18.x
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements_dbt_${{ matrix.dbt-version }}.txt
      # There is more than one target in profiles.yml because
      # dbt-sqlite for dbt~=0.18.x uses a different format than other
      # versions.
      - name: Run tests for dbt~=0.18.x
        if: ${{ matrix.dbt-version == '0.18.x' }}
        env:
          TARGET: ${{ matrix.dbt-version }}
        run: |
          python tests/test.py
      - name: Run tests for other dbt versions
        if: ${{ matrix.dbt-version != '0.18.x' }}
        env:
          TARGET: default
        run: |
          python tests/test.py
