name: test
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        dbt-version: [0.18.x, 0.19.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install -r requirements/requirements_dbt_${{ matrix.dbt-version }}.txt
      - name: Check formatting with Black
        run: |
          black --check -S -l 79
      - name: Run tests
        run: |
          python tests/test.py